{{- range untilStep 1 (int .Values.numApplications) 1 }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app-{{ . }}
  namespace: test-app-{{ . }}
  # namespace: {{ default "argocd" $.Values.namespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: test-app-{{ . }}
    server: https://kubernetes.default.svc
  project: {{ default "default" $.Values.project }}
  source:
    path: test-app-{{ . }}
    repoURL: https://github.com/ciiay/test-multi-app
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
 {{- end }}
